# Generated by Django 4.1 on 2023-01-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
